### ISSUE TITLE
Python 3 ERROR

### ISSUE THREAD

**Issue by ghost** [athena-voice/athena-voice-client#47]
I am using Linux Mint.
After I run " from athena import__main__", 
this happens:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'athena'

What do I do? I think I have installed everything given on the installation documentation page.

**Comment by rcbyron** [comment]
This error means "athena" is not in your sys.path (or PYTHONPATH)
Make sure that the HeyAthena package got installed to the correct python location. You might have a mix-up between Python 2 and 3.
The installation instructions say to run "pip3 install HeyAthena" but pip3 is only for python 3. Use pip2 or just pip if you are running Python 2.

You can also verify where it is installed:
Run "which python" to find your installation directory
Switch to that directory and look for Lib > site-packages > athena
If the folder is not there, then it is not installed correctly

**Comment by ghost** [comment]
Hey I followed your instructions and managed to install Athena in python 2.7 however Athena is getting installed in dist-packages instead of site-packages and I'm getting the following error when try to import **main** : 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/athena/**main**.py", line 2, in <module>
    from athena import brain
  File "/usr/local/lib/python2.7/dist-packages/athena/brain.py", line 62
    print('\n~ Module Order: ', end='')
                                   ^
SyntaxError: invalid syntax
Please help.

**Comment by rcbyron** [comment]
This was a python 2 compatibility issue. It should be fixed now. Post another issue if you still have errors. Thanks!
