### ISSUE TITLE
No module named '_sphinxbase'

### ISSUE THREAD

**Issue by darrindickey** [athena-voice/athena-voice-client#48]
I'm using the Developer (GitHub) Installation. When I run `python3 __main__.py` I get this error:
ImportError: No module named '_sphinxbase'

I'm wondering if this has something to do with: 
"Pocketsphinx (SWIG required in your PATH during installation)"

If so, does this mean I need PATH="/path/to/swig" in my bash_profile? I tried that and it didn't seem to work.

**Comment by rcbyron** [comment]
Sorry for just now getting back to you. I believe pocketsphinx/sphinxbase are only used in the stt.py (speech-to-text) file:
```
from sphinxbase.sphinxbase import Config, Config_swigregister
from pocketsphinx.pocketsphinx import Decoder
```
Were you able to "pip3 install pocketsphinx" without errors? This is the part that should need swig (for porting parts to python).
