### ISSUE TITLE
https://heyathena.com/ is down

### ISSUE THREAD

**Issue by Akibo95** [athena-voice/athena-voice-client#50]
On attempting to open the website linked on this project's home page, I received a "secure connection failed" message. The web server apparently failed to respond as no information about the response was captured by my browser.

**Comment by rcbyron** [comment]
Yes, the main website is currently down due to server issues (sorry about that!)

I put up a temporary website at [http://tiny.cc/heyathena](http://tiny.cc/heyathena) so that people can still use the docs. I will work on getting this fixed soon :)

**Comment by rcbyron** [comment]
Website is back up :)

I also put up a forum for discussing Hey Athena related topics.
