### ISSUE TITLE
Athena is triggered by background noises

### ISSUE THREAD

**Issue by ghost** [athena-voice/athena-voice-client#55]
Not even speaking, too. Just noises.

This doesn't happen on the distribution version, but when I run it from source, the issue happens.

**Comment by rcbyron** [comment]
In the latest version on github, you have to manually set the threshold depending on your ambient mic/noise level. To do this, you can edit the "athena/keyphrases.txt" file and change the values:
athena /1e-30/
to something like athena /1e-20/ or athena /1e-10/ (less sensitive)
(or up to around /1e-60/ if you need it to detect more easily)

The wake-up-word/keyphrases use pocketsphinx behind the scenes. I'm hoping to find a way to auto-adjust the thresholds soon (e.g. have a background thread adjust for the ambient noise level... then if false triggers still occur, the user can respond saying "false trigger" and athena will adjust to a lower sensitivity threshold"

**Comment by ghost** [comment]
I see. I've just been editing the modules in my dist-packages directory lol. Thank you for answering!
