### ISSUE TITLE
Active Listening "Beep" sould not interrupt the tts engine

### ISSUE THREAD

**Issue by dimitrisTim** [athena-voice/athena-voice-client#61]
When Athena is talking (the tts engine), the active listening "beep"  sound should not interrupt her speech. I find it a bit irritating, because I want to listen to the whole speech she is making. Would it be a good idea to implement? I think I could do that If you want.

**Comment by rcbyron** [comment]
I think this is an issue with running the "beep" sound on a separate processing thread. I did this to speed things up. If you have a better solution for triggering a beep in python, please let me know. I would be happy to merge your solution into the repository if it works well.

**Comment by dimitrisTim** [comment]
So, I managed to do it by using the Sound class of pygame instead of the Music. Also I changed the sound files to wav, because the Sound class only accepts .wav or .ogg. By doing that, it is possible to play more than one sound files at the same time, so mission accomplished ;) I can do a pull-request on the next days!
