### ISSUE TITLE
sathish

### ISSUE THREAD

**Issue by isathish** [athena-voice/athena-voice-client#62]
Hi have following questions:
1. If its client application so server will be and code server code ?
2. How we can rename to athena to our own name ?
3. I want to extent the selenium code for continus testing automation?
4. we want to inter-grate with node-red for coversiontns 

Please answer me asap

**Comment by rcbyron** [comment]
Apologies for the late reply:
1. The client doesn't really have a dedicated server counterpart. It just uses some services like Google Speech-to-Text and Text-to-Speech. A server might be a future addition.
2. I believe this is done by editing the "keyphrases.txt" file... and changing the WAKE_UP_WORD variable in "settings.py"
3. Feel free to integrate with Selenium as you wish. This is an open source project.
4. I am not sure what Node-Red is.

Cheers
