### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Suleman-Elahi** [athena-voice/athena-voice-client#66]
As of now on 12 Feb 2018, the website doesn't seem to work.

![image](https://user-images.githubusercontent.com/24384996/36084639-289a0414-0fe5-11e8-91d5-c3520d0fadb5.png)

Hope, it will be fixed soon.

**Comment by jleaders** [comment]
![screenshot from 2018-04-03 13-23-03](https://user-images.githubusercontent.com/2430917/38274001-4b48d39e-3742-11e8-89fa-2c79ba6f31cd.png)
The forwarding isn't setup properly for HTTPS (I get connection not secure error)
https://heyathena.com/
but works for HTTP
http://heyathena.com/
`certbot`  or `caddy` will fix this for you fast

also minor typo: "   -  64-bit: ``wget wget https://github.com/downloads/AVbin/AVbin/install-avbin-linux-x86-64-v10``" should only have one wget here: http://heyathena.com/docs/_sources/intro/install.rst.txt

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/52528718-f8cb2180-2cdc-11e9-8bcd-497d63c30b96.png)
![image](https://user-images.githubusercontent.com/13716824/52528725-15675980-2cdd-11e9-9fb1-29d9b3ad8948.png)


For me both HTTPS and HTTP aren't working.
